//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetStudioGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsMainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsMainForm() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssetStudioGUI.Properties.StringsMainForm", typeof(StringsMainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 %Exporting% 的本地化字符串。
        /// </summary>
        internal static string Export_Exporting {
            get {
                return ResourceManager.GetString("Export_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Restart_To_Apply% 的本地化字符串。
        /// </summary>
        internal static string LangSet_OkMessageboxText {
            get {
                return ResourceManager.GetString("LangSet_OkMessageboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Change_Lang% 的本地化字符串。
        /// </summary>
        internal static string LangSet_OkMessageboxTitle {
            get {
                return ResourceManager.GetString("LangSet_OkMessageboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %{0}%{1}% 的本地化字符串。
        /// </summary>
        internal static string Load_FinishLoading {
            get {
                return ResourceManager.GetString("Load_FinishLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %No_Product_Name% 的本地化字符串。
        /// </summary>
        internal static string Load_NoProductName {
            get {
                return ResourceManager.GetString("Load_NoProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Format% 的本地化字符串。
        /// </summary>
        internal static string Preview_Audio_formatHead {
            get {
                return ResourceManager.GetString("Preview_Audio_formatHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %GL_Help% 的本地化字符串。
        /// </summary>
        internal static string Preview_GL_info {
            get {
                return ResourceManager.GetString("Preview_GL_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %GL_Not_Supported% 的本地化字符串。
        /// </summary>
        internal static string Preview_GL_unable {
            get {
                return ResourceManager.GetString("Preview_GL_unable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Localization_Failed% 的本地化字符串。
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
